# Generated by Django 5.2.8 on 2025-11-18 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'verbose_name': 'Tipo de Membresía', 'verbose_name_plural': 'Tipos de Membresía'},
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gymapp.membershiptype', verbose_name='Tipo de Membresía')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía Asignada',
                'verbose_name_plural': 'Membresías Asignadas',
            },
        ),
    ]
