# Generated by Django 5.2.8 on 2025-11-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_membershiptype_terms_entradainventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptype',
            name='terms',
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
