# Generated by Django 5.2.8 on 2025-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_miembro_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='qr_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código QR'),
        ),
    ]
