# Generated by Django 5.2.8 on 2025-11-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_asistencia_fecha_hora_salida_miembro_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='avatar_color',
            field=models.CharField(default='#1D4ED8', max_length=7),
        ),
    ]
