# Generated by Django 5.2.8 on 2025-11-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_healthprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='info_adicional',
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='lesiones_recientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='medicamentos',
            field=models.BooleanField(default=False),
        ),
    ]
