"""
Django settings for gym project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar entorno
IS_RENDER = 'RENDER' in os.environ
IS_PRODUCTION = IS_RENDER or os.environ.get('ENVIRONMENT') == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_*o4hd8w_83i4di_k@5_%zg_==y3*&%0b8_bohf&iv$y^hv^8d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['fitdata-api.onrender.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps de terceros que instalamos
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_vite',

    # Nombre de la app
    'gymapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST BE FIRST
    'gym.cors_middleware.SimpleCorsMiddleware',  # Nuestro middleware de CORS garantizado
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://pruebafitdatagym.netlify.app",
    "https://fit-data-gym.vercel.app",
]

# Permitir credenciales (tokens, cookies)
CORS_ALLOW_CREDENTIALS = True

# Fuerza que corsheaders maneje TODO (incluso errores)
CORS_ALLOW_ALL_ORIGINS = False
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
# Permitir métodos HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Permitir headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS en desarrollo: Permitir todo
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOWED_ORIGINS = []  # Se ignora si CORS_ALLOW_ALL_ORIGINS = True
else:
    # En producción, SIEMPRE permitir los orígenes específicos
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://pruebafitdatagym.netlify.app",
        "https://fit-data-gym.vercel.app",
    ]

# CSRF Configuration para CORS
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://pruebafitdatagym.netlify.app",
    "https://fit-data-gym.vercel.app",
    "https://fitdata-api.onrender.com",
]

# Permitir CSRF desde orígenes de confianza
CSRF_COOKIE_SECURE = IS_PRODUCTION  # Solo HTTPS en producción
CSRF_COOKIE_HTTPONLY = False  # Permitir acceso desde JS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_AGE = 31449600  # 1 año

ROOT_URLCONF = 'gym.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if os.environ.get('DATABASE_URL') is not None:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    # Solo en Render, forzamos la conexión segura para PostgreSQL
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}

# Si no, usamos la configuración local (SQL Server o SQLite)
else:
    DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'FitDataDB', # <-- El nombre de la DB que vas a crear
        'HOST': r'(local)',   # <-- Tu "Server Name" es (local)
        
        # --- Datos de tu captura ---
        'USER': 'ArturoBD', # <-- Tu usuario
        'PASSWORD': 'chichu2006', # <-- Escribe el password que usas
        
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'encrypt': 'yes', # <-- Vemos 'Mandatory' en tu captura
            'trust_server_certificate': 'yes', # <-- Vemos que marcaste esto
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuración de idioma y codificación
LANGUAGE_CODE = 'es-mx' # O 'es-es'
TIME_ZONE = 'America/Mexico_City' # Ajusta a tu zona
USE_I18N = True
USE_TZ = True

# Asegurar UTF-8 en la respuesta JSON
DEFAULT_CHARSET = 'utf-8'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Define dónde se coleccionarán los archivos estáticos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- Configuración de Django-Vite --- 
DJANGO_VITE_DEV_MODE = DEBUG 

DJANGO_VITE_ASSETS_PATH = BASE_DIR / "frontend" / "dist"

STATICFILES_DIRS = [
    DJANGO_VITE_ASSETS_PATH,
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DJANGO_VITE_DEV_SERVER_HOST = "localhost"
DJANGO_VITE_DEV_SERVER_PORT = 5173
# --- Fin de la configuración de Vite ---


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Configuración para archivos estáticos en Render
# ====================================================================
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Necesario para el despliegue
if not DEBUG:
    # Collectfast es útil, pero por ahora solo necesitamos WhiteNoise
    pass


# Configuración de Correo (Producción y Local)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'artsantoss30@gmail.com') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'escp yuna xixt ikpw') 

DEFAULT_FROM_EMAIL = f'FitData GYM <{EMAIL_HOST_USER}>'