# Generated by Django 5.2.8 on 2025-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_producto_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='detalle',
        ),
        migrations.AddField(
            model_name='venta',
            name='detalle_productos',
            field=models.TextField(default='[]'),
        ),
    ]
