# Generated by Django 5.2.8 on 2025-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_remove_venta_detalle_venta_detalle_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
