# Generated by Django 5.2.8 on 2025-11-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_venta_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memberships/', verbose_name='Imagen de Tarjeta'),
        ),
    ]
