# Generated by Django 5.2.8 on 2025-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_alter_entradainventario_cantidad_miembro_asistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
