# Generated by Django 5.2.8 on 2025-11-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_miembro_avatar_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='avatar',
        ),
    ]
