# Generated by Django 5.2.8 on 2025-11-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0013_remove_miembro_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('condicion_corazon', models.BooleanField(default=False)),
                ('presion_alta', models.BooleanField(default=False)),
                ('lesiones_recientes', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('info_adicional', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='gymapp.miembro')),
            ],
            options={
                'verbose_name': 'Perfil de Salud',
                'verbose_name_plural': 'Perfiles de Salud',
            },
        ),
    ]
