import { collection, getDocs, query, where } from 'firebase/firestore';
import { db, functions } from '../firebase/config';
import {
  addTrainerReview,
  assignTrainerToClient,
  auth,
  createOrUpdateTrainerRoutine,
  createTrainerNote,
  createTrainerServiceSale,
  deleteTrainerNote,
  deleteTrainerRoutineByMember,
  ensureUserClaim,
  getAllMembers,
  getAllTrainerNotes,
  getClientTrainerAssignment,
  getCurrentUser,
  getTrainerNotesByMember,
  getTrainerReviews,
  getTrainerRoutineByMember,
  getUsers,
  getTrainerServiceSales,
  getUser,
  getUserByAuthUid,
  getUserByEmail,
  onAuthChanged,
  searchExerciseCatalog,
  updateSelfProfile,
  updateTrainerNote,
  updateUser,
  subirAdjuntoRutina,
  waitForAuthReady,
} from '../firebase';

export { db, functions };
export { collection, getDocs, query, where };
export {
  addTrainerReview,
  assignTrainerToClient,
  auth,
  createOrUpdateTrainerRoutine,
  createTrainerNote,
  createTrainerServiceSale,
  deleteTrainerNote,
  deleteTrainerRoutineByMember,
  ensureUserClaim,
  getAllMembers,
  getAllTrainerNotes,
  getClientTrainerAssignment,
  getCurrentUser,
  getTrainerNotesByMember,
  getTrainerReviews,
  getTrainerRoutineByMember,
  getUsers,
  getTrainerServiceSales,
  getUser,
  getUserByAuthUid,
  getUserByEmail,
  onAuthChanged,
  searchExerciseCatalog,
  updateSelfProfile,
  updateTrainerNote,
  updateUser,
  subirAdjuntoRutina,
  waitForAuthReady,
};